name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Check 1.15.2 NMS existence
        id: check_nms
        uses: andstor/file-existence-action@v1
        with:
          files: "/home/runner/.m2/repository/org/spigotmc/spigot/1.15.2-R0.1-SNAPSHOT/spigot-1.15.2-R0.1-SNAPSHOT.pom"
      - name: Download BuildTools
        if: steps.check_nms.outputs.files_exists == 'false'
        run: mkdir -p ./build/ && curl -L -o ./build/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Run BuildTools
        if: steps.check_nms.outputs.files_exists == 'false'
        run: cd build && java -jar BuildTools.jar --rev 1.15.2
      - name: Prepare gradle.properties
        run: |
          mkdir -p $HOME/.gradle
          echo "repoUsername=${{ secrets.REPO_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "repoPassword=${{ secrets.REPO_PASSWORD }}" >> $HOME/.gradle/gradle.properties
      - name: Deploy
        run: ./gradlew clean test publish
